#!/bin/bash

#SBATCH -p aspuru-guzik
#SBATCH -n 1 
#SBATCH -t 24:00:00 
#SBATCH --mem=4000
#SBATCH -o morgan3_balanced_100each_100run.test
#SBATCH -e morgan3_balanced_100each_100run.err
#SBATCH -J morgan3_bal_100each 

# To check:
#  - copy data files
#  - Data file percent matches train percent (and file names in hypopt file)
#  - fp type is correct and consistent in sub and hypopt

scfolder="/scratch/$(date +%Y%m%d%H%M)_10k_50enr_prod3/"
curr=$(pwd)

# Create scratch folder on cluster space
mkdir -p  $scfolder

#edit these
cp fp1_double_hypopt_rxn_predict.py $scfolder 
cp fp1_double_reaction_estimator.py $scfolder
# prod3
cp ~/reaction_learn/data/balanced_set/200each_class_3_2/balanced_200each_train_inputs_3.dat $scfolder/train_inputs.dat
cp ~/reaction_learn/data/balanced_set/200each_class_3_2/balanced_200each_train_targets.dat $scfolder/train_targets.dat

# execute python 
cd $scfolder

python -u fp1_double_hypopt_rxn_predict.py > $curr/output/morgan3_balanced_100each_train_norm_100run.out

# retrieve files back to local directory.
cd
mkdir -p  $curr/output/
cp  $scfolder/morgan*  $curr/output/
rm -r $scfolder/
