#!/bin/bash

#SBATCH -p aspuru-guzik
#SBATCH -n 1 
#SBATCH -t 24:00:00 
#SBATCH --mem=2000
#SBATCH -o morgan2_balanced_200each.test
#SBATCH -e morgan2_balanced_200each.err
#SBATCH -J morgan_bal_200each_2 

# To check:
#  - copy data files
#  - Data file percent matches train percent (and file names in hypopt file)
#  - fp type is correct and consistent in sub and hypopt

scfolder="/scratch/$(date +%Y%m%d%H%M)_morgan_bal_200each_2/"
curr=$(pwd)

# Create scratch folder on cluster space
mkdir -p  $scfolder

#edit these
cp fp1_morgan_hypopt_rxn_predict.py $scfolder 
cp fp1_reaction_estimator.py $scfolder

cp ~/reaction_learn/data/balanced_set/200each_class_3_2/balanced_200each_train_inputs_2.dat $scfolder/train_inputs.dat
cp ~/reaction_learn/data/balanced_set/200each_class_3_2/balanced_200each_train_targets.dat $scfolder/train_targets.dat

# execute python 
cd $scfolder

python -u fp1_morgan_hypopt_rxn_predict.py > $curr/output/morgan2_balanced_200each_train_norm.out

# retrieve files back to local directory.
cd
mkdir -p  $curr/output/
cp  $scfolder/morgan*  $curr/output/
rm -r $scfolder
